//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.MuonSaches = new HashSet<MuonSach>();
        }
    
        public string matk { get; set; }
        public string tendangnhap { get; set; }
        public string matkhau { get; set; }
        public string tentaikhoan { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public string diachi { get; set; }
        public Nullable<int> loaitaikhoan { get; set; }
    
        public virtual LoaiTaiKhoan LoaiTaiKhoan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuonSach> MuonSaches { get; set; }
    }
}
